import { readFileSync, readdirSync } from 'node:fs'
import { join, relative } from 'node:path'
import { expect, it } from 'vitest'

const renderer = new URL('../src/renderer/src/', import.meta.url).pathname
function sourceFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name)
    return entry.isDirectory() ? sourceFiles(path) : entry.name.endsWith('.tsx') ? [path] : []
  })
}

it('keeps PMO teams on one bottom entry and one canonical Topic', () => {
  const entry = readFileSync(join(renderer, 'components/PmoTeamsTopicEntry.tsx'), 'utf8')
  const panel = readFileSync(join(renderer, 'components/PmoTeamsTopicFloatingPanel.tsx'), 'utf8')
  const styles = readFileSync(join(renderer, 'styles/pmo-teams-topic.css'), 'utf8')
  const app = readFileSync(join(renderer, 'App.tsx'), 'utf8')
  const workbench = readFileSync(join(renderer, 'components/WorkspaceWorkbench.tsx'), 'utf8')
  const chrome = readFileSync(join(renderer, 'styles/agent.css'), 'utf8')
  const navigation = readFileSync(join(renderer, 'components/SurfaceNavigation.tsx'), 'utf8')
  const shared = readFileSync(new URL('../src/shared/scratch-topics.ts', import.meta.url), 'utf8')
  expect(entry).toContain('requestPmoTeamsTopicFloatingOpen')
  expect(entry).toContain('pmo-teams-topic-compact-launcher')
  expect(entry).toContain('pmoTeamsTopicAvatar')
  expect(entry).toContain('aria-expanded={floating.open}')
  expect(entry).toContain('requestPmoTeamsTopicFloatingClose')
  expect(entry).not.toContain('launcherPlacement')
  expect(entry).not.toContain('data-pmo-teams-topic-mode')
  expect(styles).not.toContain('pmo-teams-topic-floating-launcher')
  expect(styles).toContain('pmo-teams-topic-floating--opening::after')
  expect(styles).toContain('pmo-teams-topic-signal')
  expect(styles).toContain('pmo-teams-topic-firework-left')
  expect(styles).toContain('pmo-teams-topic-firework-right')
  expect(styles).toContain('pmo-teams-topic-compact-launcher__firework i:nth-child(6)')
  expect(styles).toContain('prefers-reduced-motion')
  expect(chrome).toContain('.surface-navigation__slot--launcher')
  const launcher = chrome.match(/\.surface-navigation__slot--launcher\s*\{([^}]+)\}/)
  expect(launcher).not.toBeNull()
  expect(launcher![1]).toContain('border-radius: 10px')
  const burst = styles.match(/\.pmo-teams-topic-compact-launcher__firework i\s*\{([^}]+)\}/)
  expect(burst).not.toBeNull()
  expect(burst![1]).toContain('animation-iteration-count: 1')
  expect(chrome).not.toContain('.window-status-bar__pmo-entry')
  expect(styles).toContain('.pmo-teams-topic-floating__titlebar--attached')
  expect(styles).toContain('height: 34px')
  expect(styles).toContain('font-size: var(--fs-micro)')
  expect(panel).toContain('api.scratch.ensureTopic(SCRATCH_WORKSPACE_ID, PMO_TEAMS_TOPIC_ID)')
  expect(panel).toContain('api.scratch.renameTitle(SCRATCH_WORKSPACE_ID, PMO_TEAMS_TOPIC_ID, PMO_TEAMS_TOPIC_TITLE)')
  expect(panel).toContain('openScratchTopic(PMO_TEAMS_TOPIC_ID, SCRATCH_WORKSPACE_ID, {')
  expect(panel).toContain('tabId: floating.targetTabId')
  expect(panel).toContain('topicId={PMO_TEAMS_TOPIC_ID}')
  expect(panel).toContain('requestPmoTeamsTopicFloatingClose')
  expect(panel).toContain('id="pmo-teams-topic-floating-panel"')
  expect(panel).not.toContain('launcherPosition')
  expect(panel).not.toContain('openAnchor')
  expect(app).toContain('<PmoTeamsTopicFloatingPanel />')
  expect(app).toContain('<SurfaceSwitch />')
  expect(app).not.toContain('window-status-bar__pmo-entry')
  expect(navigation).toContain("id: 'pmo-teams'")
  expect(navigation).toContain('<PmoTeamsTopicEntry placement="compact" />')
  expect(workbench).toContain('topicId?: string')
  expect(shared).toContain("PMO_TEAMS_TOPIC_ID = 'launcher:leader'")
  const callers = sourceFiles(renderer).filter((file) => readFileSync(file, 'utf8').includes('<PmoTeamsTopicEntry'))
  expect(callers.map((file) => relative(renderer, file)).sort()).toEqual(['components/SurfaceNavigation.tsx'])
})

it('uses the shipped AgentMux dragon asset for the PMO teams topic launcher', () => {
  const launcherAsset = readFileSync(join(renderer, 'assets/pmo-teams-topic-avatar.png'))
  const projectAsset = readFileSync(new URL('../resources/icon.png', import.meta.url))
  expect(launcherAsset.equals(projectAsset)).toBe(true)
})

it('keeps PMO dragging in a frame-synchronous visual preview until pointer end', () => {
  const panel = readFileSync(join(renderer, 'components/PmoTeamsTopicFloatingPanel.tsx'), 'utf8')
  const moveStart = panel.indexOf('const onPanelPointerMove')
  const moveEnd = panel.indexOf('const onPanelPointerEnd', moveStart)
  const frameStart = panel.indexOf('const renderDragFrame')
  const frameEnd = panel.indexOf('const scheduleDragFrame', frameStart)
  expect(moveStart).toBeGreaterThan(-1)
  expect(moveEnd).toBeGreaterThan(moveStart)
  expect(frameStart).toBeGreaterThan(-1)
  expect(frameEnd).toBeGreaterThan(frameStart)
  const move = panel.slice(moveStart, moveEnd)
  const frame = panel.slice(frameStart, frameEnd)
  expect(move).toContain('scheduleDragFrame()')
  expect(move).not.toContain('setFloating(')
  expect(move).not.toContain('onUpdate(')
  expect(frame).toContain('panelRef.current.style.transform')
  expect(panel).toContain('window.requestAnimationFrame(renderDragFrame)')
  expect(panel).toContain('onUpdate({ position: next.position })')
  expect(panel).not.toContain('Request routing')
})
