import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import fs from 'node:fs/promises'
import path from 'node:path'
import ts from 'typescript'
import { describe, expect, it, vi } from 'vitest'

const source = readFileSync(new URL('../scripts/verify-terminal-live-scroll.mjs', import.meta.url), 'utf8')
function actualPreservation() {
  const file = ts.createSourceFile('verify-terminal-live-scroll.mjs', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.JS)
  expect(file.parseDiagnostics).toHaveLength(0)
  const functions = file.statements.filter((node): node is ts.FunctionDeclaration => ts.isFunctionDeclaration(node) && node.name?.text === 'preserveGeneratedArtifacts')
  const owners = file.statements.filter((node): node is ts.TryStatement => ts.isTryStatement(node) && Boolean(node.finallyBlock))
  expect(functions).toHaveLength(1)
  expect(owners).toHaveLength(1)
  expect(functions[0]!.body!.statements.length).toBeGreaterThan(0)
  expect(owners[0]!.finallyBlock!.statements.length).toBeGreaterThan(0)
  return { helper: functions[0]!.getText(file), consumer: owners[0]!.finallyBlock!.statements.map(node => node.getText(file)).join('\n') }
}
const hash = (value: Buffer) => createHash('sha256').update(value).digest('hex')
async function fixture() {
  const base = await fs.mkdtemp('/tmp/amx-terminal-source-evidence-')
  const privateRoot = path.join(base, 'private-owner'), captureDirectory = path.join(base, 'captures')
  const inputs = new Map([
    [path.join(privateRoot, 'renderer/assets/generated.js'), Buffer.from([0, 255, 1, 128, 13, 10])],
    [path.join(privateRoot, 'native-items.json'), Buffer.from('  [{"id":"private-item"}]\n')],
    [path.join(privateRoot, 'native-reader.mjs'), Buffer.from('process.stdout.write("private reader");\n')],
    [path.join(privateRoot, 'reader.ndjson'), Buffer.from('{"kind":"start"}\n{"kind":"eof"}\n')]
  ])
  for (const [file, bytes] of inputs) { await fs.mkdir(path.dirname(file), { recursive: true }); await fs.writeFile(file, bytes) }
  await fs.mkdir(captureDirectory)
  const distributionArtifacts = Object.fromEntries([...inputs].filter(([file]) => file.includes('/renderer/')).map(([file, bytes]) => [file, hash(bytes)]))
  const nativeFixture = Object.fromEntries([...inputs].filter(([file]) => ['native-items.json', 'native-reader.mjs'].includes(path.basename(file))).map(([file, bytes]) => [file, hash(bytes)]))
  const result: any = { passed: true, distributionArtifacts, nativeFixture, cleanup: { remaining: null, rootRemoved: false, errors: [] } }
  const cleanupOwnedProbes = vi.fn(async (_root: string) => ({ remaining: [], errors: [] }))
  const actual = actualPreservation(), receiptPath = path.join(captureDirectory, 'original-receipt.json')
  const globals = { assert, fs, path, createHash, result, privateRoot, captureDirectory, receiptPath, cleanupOwnedProbes,
    clearTimeout: vi.fn(), timer: null, console: { log: vi.fn() } }
  const run = new Function(...Object.keys(globals), `${actual.helper}\nreturn async () => {${actual.consumer}\n}`)(...Object.values(globals)) as () => Promise<void>
  return { base, privateRoot, captureDirectory, inputs, distributionArtifacts, nativeFixture, result, run, cleanupOwnedProbes, receiptPath }
}

describe('actual terminal Native generated evidence consumer', () => {
  it('preserves original generated bytes before removing their private owner and leaves old hash keys intact', async () => {
    const x = await fixture()
    try {
      await x.run()
      expect(x.result.passed).toBe(true)
      expect(x.result.cleanup).toEqual({ remaining: [], rootRemoved: true, errors: [] })
      expect(x.cleanupOwnedProbes.mock.calls).toEqual([[x.privateRoot]])
      expect(x.result.preservedGeneratedArtifacts).toBeTruthy()
      const saved = x.result.preservedGeneratedArtifacts
      expect(saved.schema).toBe('agentmux.terminal-live-scroll-preserved-artifacts.v1')
      expect(saved.distributionArtifacts).toHaveLength(1)
      expect(saved.nativeFixture).toHaveLength(2)
      expect(saved.nativeReaderTrace).toBeTruthy()
      const refs = [...saved.distributionArtifacts, ...saved.nativeFixture, saved.nativeReaderTrace]
      expect(refs.map(item => item.originalPath)).toEqual([...x.inputs.keys()])
      for (const item of refs) {
        const bytes = await fs.readFile(item.path)
        expect(bytes).toEqual(x.inputs.get(item.originalPath))
        expect(item.sha256).toBe(hash(bytes)); expect(item.byteLength).toBe(bytes.length)
        expect(item.path.startsWith(path.join(x.captureDirectory, 'generated-inputs') + path.sep)).toBe(true)
      }
      await expect(fs.stat(x.privateRoot)).rejects.toMatchObject({ code: 'ENOENT' })
      expect(x.result.distributionArtifacts).toBe(x.distributionArtifacts)
      expect(x.result.nativeFixture).toBe(x.nativeFixture)
      expect(JSON.parse(await fs.readFile(x.receiptPath, 'utf8')).preservedGeneratedArtifacts).toEqual(saved)
    } finally { await fs.rm(x.base, { recursive: true, force: true }) }
  })

  it('rejects changed generated input bytes and keeps the original owner for honest failed evidence', async () => {
    const x = await fixture()
    try {
      const file = [...x.inputs.keys()][0]!
      await fs.writeFile(file, 'changed after original generated hash')
      await x.run()
      expect(x.result.passed).toBe(false)
      expect(x.result.cleanup.rootRemoved).toBe(false)
      expect(x.result.cleanup.errors).toHaveLength(1)
      expect(x.result.cleanup.errors[0]).toContain('Generated Native input changed before preservation')
      expect(x.result.artifactPreservationFailure).toContain('AssertionError')
      expect((await fs.stat(x.privateRoot)).isDirectory()).toBe(true)
      expect(x.result.distributionArtifacts).toBe(x.distributionArtifacts)
      expect(x.result.nativeFixture).toBe(x.nativeFixture)
    } finally { await fs.rm(x.base, { recursive: true, force: true }) }
  })
})
